version: '3'

services:
  prometheus:
    image: linkuanhao/prometheus:v1
    ports:
      - "9090:9090"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  grafana:
    image: linkuanhao/grafana:v1
    ports:
      - "3000:3000"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  node-exporter:
    image: linkuanhao/node-exporter:v1
    ports:
      - "9100:9100"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
